#!/usr/bin/env python3
"""
embed_static.py — Build script for ExcelManus Setup UI

Reads the Vite single-file build output (setup-ui/dist/index.html)
and generates EmbeddedAssets.cs with the HTML inlined as a C# string constant.

Usage:
    cd deploy/
    cd setup-ui && npm run build && cd ..
    python embed_static.py
    # → produces EmbeddedAssets.cs

Then compile:
    csc.exe /langversion:5 /target:winexe /out:ExcelManus.exe ExcelManusSetup.cs EmbeddedAssets.cs
"""

import os
import sys

DIST_DIR = os.path.join(os.path.dirname(__file__), "setup-ui", "dist")
OUTPUT_CS = os.path.join(os.path.dirname(__file__), "EmbeddedAssets.cs")


def escape_cs_verbatim(s: str) -> str:
    """Escape a string for use inside a C# @\"...\" verbatim string literal.
    The only character that needs escaping is double-quote → double double-quote.
    """
    return s.replace('"', '""')


def main():
    index_html = os.path.join(DIST_DIR, "index.html")
    if not os.path.isfile(index_html):
        print(f"ERROR: {index_html} not found.", file=sys.stderr)
        print("Run 'cd setup-ui && npm run build' first.", file=sys.stderr)
        sys.exit(1)

    html_content = open(index_html, "r", encoding="utf-8").read()
    size_kb = len(html_content.encode("utf-8")) / 1024

    escaped = escape_cs_verbatim(html_content)

    cs_code = f'''// Auto-generated by embed_static.py — DO NOT EDIT
// Source: setup-ui/dist/index.html ({size_kb:.1f} KB)

public static class EmbeddedAssets
{{
    public static readonly string IndexHtml = @"{escaped}";
}}
'''

    with open(OUTPUT_CS, "w", encoding="utf-8") as f:
        f.write(cs_code)

    print(f"Generated {OUTPUT_CS}")
    print(f"  HTML size: {size_kb:.1f} KB")
    print(f"  CS file:   {os.path.getsize(OUTPUT_CS) / 1024:.1f} KB")


if __name__ == "__main__":
    main()
