import { ArrowRight, Brain, Clock, Eye, Gauge, Layers, Shield, Sparkles, ToggleLeft, Bot, Terminal, Timer, Zap } from "lucide-react";
import type { RuntimeSettingGroup } from "@/lib/runtime-settings-form";

// Form rendering and search share these definitions to prevent labels from drifting.
export const SECURITY_SETTING_GROUPS: RuntimeSettingGroup[] = [
  {
    title: "代码执行与工具校验",
    description: "设置 Agent 执行代码和调用工具时的风险分级、自动放行范围与参数检查。",
    icon: <Shield className="h-4 w-4" />,
    items: [
      {
        key: "code_policy_enabled",
        label: "代码风险分级",
        desc: "按绿 / 黄 / 红等级判断代码是自动运行还是先请求确认；新任务生效。",
        icon: <Shield className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "code_policy_green_auto_approve",
        label: "低风险代码自动执行",
        desc: "自动执行低风险代码，并继续限制网络、子进程和工作区外写入。",
        disabledDesc: "开启代码风险分级后可设置。",
        disabledWhen: (settings) => !settings.code_policy_enabled,
        icon: <Shield className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "code_policy_yellow_auto_approve",
        label: "中风险代码自动执行",
        desc: "自动执行中风险代码；仍不会自动批准文件系统写入。",
        disabledDesc: "开启代码风险分级后可设置。",
        disabledWhen: (settings) => !settings.code_policy_enabled,
        icon: <Shield className="h-4 w-4" />,
        type: "bool",
      },
    ],
  },
  {
    title: "开发者工具校验", description: "用于排查工具调用协议问题，通常无需调整。",
    icon: <Shield className="h-4 w-4" />, defaultOpen: false,
    items: [
      {
        key: "tool_schema_validation_mode",
        label: "工具参数校验",
        desc: "影子模式只记录问题；强制模式会拒绝不合规参数。新任务生效。",
        icon: <Shield className="h-4 w-4" />,
        type: "select",
        options: [
          { value: "off", label: "关闭" },
          { value: "shadow", label: "仅记录" },
          { value: "enforce", label: "强制" },
        ],
      },
      {
        key: "tool_schema_validation_canary_percent",
        label: "强制校验比例",
        desc: "强制模式下实际拦截的请求比例；其他请求按仅记录处理。",
        disabledDesc: "选择强制校验后可调整。",
        disabledWhen: (settings) => settings.tool_schema_validation_mode !== "enforce",
        icon: <Gauge className="h-4 w-4" />,
        type: "int",
        min: 0,
        max: 100,
        unit: "%",
      },
      {
        key: "tool_schema_strict_path",
        label: "严格路径校验",
        desc: "拒绝工具参数中的绝对路径和上级目录穿越。",
        disabledDesc: "开启工具参数校验后可设置。",
        disabledWhen: (settings) => settings.tool_schema_validation_mode === "off",
        icon: <Shield className="h-4 w-4" />,
        type: "bool",
      },
    ],
  },
];

export const MEMORY_SETTING_GROUPS: RuntimeSettingGroup[] = [
  {
    title: "记忆配置",
    description: "控制跨任务记忆的读写、保留时间和自动维护。已有条目不会因关闭功能而删除。",
    icon: <Brain className="h-4 w-4" />,
    items: [
      {
        key: "memory_enabled",
        label: "跨会话记忆",
        desc: "允许 Agent 在新任务中读取并沉淀长期信息；新开任务后完全生效。",
        icon: <ToggleLeft className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "memory_auto_load_lines", label: "每次加载的记忆行数", type: "int", min: 1, unit: "行",
        desc: "新对话启动时最多读取的记忆内容。值越大，占用的对话容量越多。",
        disabledWhen: (settings) => !settings.memory_enabled,
      },
      {
        key: "memory_expire_days",
        label: "记忆过期天数",
        desc: "任务启动时清理超过此天数的记忆；0 表示不过期。",
        icon: <Clock className="h-4 w-4" />,
        type: "int",
        min: 0,
        unit: "天",
        disabledWhen: (settings) => !settings.memory_enabled,
      },
    ],
  },
  {
    title: "自动维护",
    description: "在记忆积累到一定规模后自动合并重复内容并清理低价值条目。",
    icon: <Sparkles className="h-4 w-4" />,
    defaultOpen: false,
    items: [
      {
        key: "memory_maintenance_enabled",
        label: "记忆自动维护",
        desc: "提取新记忆后，按条目数、增量和间隔执行维护。",
        disabledDesc: "请先开启跨会话记忆。",
        disabledWhen: (settings) => !settings.memory_enabled,
        icon: <Sparkles className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "memory_maintenance_min_entries",
        label: "维护最少条目数",
        desc: "记忆少于此数时不触发维护。",
        disabledDesc: "开启记忆自动维护后可调整。",
        disabledWhen: (settings) => !settings.memory_enabled || !settings.memory_maintenance_enabled,
        icon: <Layers className="h-4 w-4" />,
        type: "int",
        min: 1,
        unit: "条",
      },
      {
        key: "memory_maintenance_new_threshold",
        label: "维护新增阈值",
        desc: "新增条目达到此数后才可能触发维护。",
        disabledDesc: "开启记忆自动维护后可调整。",
        disabledWhen: (settings) => !settings.memory_enabled || !settings.memory_maintenance_enabled,
        icon: <Layers className="h-4 w-4" />,
        type: "int",
        min: 1,
        unit: "条",
      },
      {
        key: "memory_maintenance_interval_hours",
        label: "维护最小间隔",
        desc: "两次维护之间的最短间隔（小时）。",
        disabledDesc: "开启记忆自动维护后可调整。",
        disabledWhen: (settings) => !settings.memory_enabled || !settings.memory_maintenance_enabled,
        icon: <Clock className="h-4 w-4" />,
        type: "float",
        min: 0.5,
        unit: "小时",
      },
      {
        key: "memory_maintenance_model",
        label: "维护模型 ID（可选）",
        desc: "留空使用当前模型。自定义 ID 必须能通过当前模型的接口和密钥调用，不能用来切换提供商。",
        disabledDesc: "开启记忆自动维护后可调整。",
        disabledWhen: (settings) => !settings.memory_enabled || !settings.memory_maintenance_enabled,
        icon: <Brain className="h-4 w-4" />,
        type: "string",
      },
    ],
  },
];

export const SKILL_SETTING_GROUPS: RuntimeSettingGroup[] = [
  {
    title: "技能发现",
    description: "选择 Agent 会从哪些兼容目录加载技能，以及每次激活技能时可注入的内容上限。",
    icon: <Sparkles className="h-4 w-4" />,
    items: [
      {
        key: "skills_discovery_enabled",
        label: "自动发现兼容目录",
        desc: "除内置和用户 / 项目目录外，还扫描其他工具常用的技能目录。",
        icon: <Sparkles className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "skills_discovery_include_agents",
        label: "加载 .agents/skills",
        desc: "扫描项目里的 .agents/skills 文件夹；此设置与子代理无关。",
        disabledDesc: "开启自动发现兼容目录后可使用。",
        disabledWhen: (settings) => !settings.skills_discovery_enabled,
        icon: <Bot className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "skills_discovery_scan_workspace_ancestors",
        label: "扫描工作区上级目录",
        desc: "从当前目录到项目根，逐层查找 .agents/skills。",
        disabledDesc: "开启自动发现兼容目录后可使用。",
        disabledWhen: (settings) => !settings.skills_discovery_enabled,
        icon: <Sparkles className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "skills_discovery_scan_external_tool_dirs",
        label: "兼容 Claude 与 OpenClaw",
        desc: "从用户目录与项目中的 Claude、OpenClaw 技能文件夹加载技能。",
        disabledDesc: "开启自动发现兼容目录后可使用。",
        disabledWhen: (settings) => !settings.skills_discovery_enabled,
        icon: <Sparkles className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "skills_discovery_extra_dirs", label: "额外技能文件夹", type: "string",
        desc: "在服务所在机器上查找技能的额外目录，多个目录用英文逗号分隔。",
        placeholder: "/path/to/skills",
        disabledWhen: (settings) => !settings.skills_discovery_enabled,
      },
      {
        key: "skills_context_char_budget",
        label: "技能注入长度上限",
        desc: "激活技能时注入对话的正文总字符上限；0 表示不限制。",
        icon: <Gauge className="h-4 w-4" />,
        type: "int",
        min: 0,
      },
    ],
  },
  {
    title: "技能 Hook",
    description: "控制技能包是否可在任务事件中运行外部命令，以及命令的资源边界。",
    icon: <Terminal className="h-4 w-4" />,
    defaultOpen: false,
    items: [
      {
        key: "hooks_command_enabled",
        label: "允许 Hook 外部命令",
        desc: "允许技能包在任务开始、用户提交、工具前后及子代理起止时运行已授权命令。",
        icon: <Terminal className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "hooks_command_allowlist", label: "允许的命令前缀", type: "string",
        desc: "多个前缀用英文逗号分隔；常规审批下留空会拒绝命令，跳过审批时不受此列表限制。仅填写可信命令前缀。",
        disabledWhen: (settings) => !settings.hooks_command_enabled,
        placeholder: "例如 python /path/to/hook.py",
      },
      {
        key: "hooks_command_timeout_seconds",
        label: "Hook 命令超时",
        desc: "外部命令最长执行时间（秒）；超时会跳过且不影响主流程。",
        disabledDesc: "允许 Hook 外部命令后可调整。",
        disabledWhen: (settings) => !settings.hooks_command_enabled,
        icon: <Timer className="h-4 w-4" />,
        type: "int",
        min: 1,
      },
      {
        key: "hooks_output_max_chars",
        label: "Hook 输出上限",
        desc: "外部命令返回内容可注入任务的最大字符数。",
        disabledDesc: "允许 Hook 外部命令后可调整。",
        disabledWhen: (settings) => !settings.hooks_command_enabled,
        icon: <Gauge className="h-4 w-4" />,
        type: "int",
        min: 1,
      },
    ],
  },
];

export const MODEL_RUNTIME_SETTING_GROUPS: RuntimeSettingGroup[] = [
  {
    title: "模型请求",
    description: "仅在接口兼容性或模型请求行为不符合预期时调整。任务时长和费用限制在「偏好与运行 → 任务限制」。",
    defaultOpen: false,
    icon: <Zap className="h-4 w-4" />,
    items: [
      {
        key: "main_model_vision",
        label: "图片识别",
        desc: "自动时按模型能力判断；模型档案中手动指定的输入模态优先于此设置。",
        icon: <Eye className="h-4 w-4" />,
        type: "select",
        options: [
          { value: "auto", label: "自动" },
          { value: "true", label: "开启" },
          { value: "false", label: "关闭" },
        ],
      },
      {
        key: "responses_continuation_enabled",
        label: "复用服务端对话状态",
        desc: "仅对 Responses 协议生效。复用服务端保存的响应，减少重复发送历史内容；需接口支持。",
        icon: <ArrowRight className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "responses_background_enabled",
        label: "使用模型接口的后台任务",
        desc: "仅对 Responses 协议生效。让接口在后台生成并等待结果；适合支持此功能的长时间推理模型。",
        icon: <Clock className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "prompt_cache_key_enabled",
        label: "发送提示词缓存标识",
        desc: "帮助支持缓存的接口复用重复内容。是否命中及如何收费由服务商决定。",
        icon: <Zap className="h-4 w-4" />,
        type: "bool",
      },
      {
        key: "prompt_cache_retention", label: "提示词缓存保留时间", type: "select",
        desc: "延长仅对 OpenAI 和 Anthropic 官方接口生效；可能改变缓存费用，兼容网关忽略此项。",
        options: [{ value: "default", label: "服务商默认（推荐）" }, { value: "extended", label: "延长保留" }],
      },
    ],
  },
  {
    title: "图片传输",
    description: "限制发送给模型的图片尺寸与编码体积，并选择 Files API 的使用方式。",
    icon: <Eye className="h-4 w-4" />,
    defaultOpen: false,
    items: [
      {
        key: "image_pixel_budget",
        validate: (value) => /^(low|[1-9]\d*)$/.test(String(value).trim().toLowerCase()) ? undefined : "请输入正整数或 low",
        label: "发送图片的像素上限",
        desc: "例如 640000。也可填写 low，使用 512×512；仅压缩发送副本，不修改原图。",
        icon: <Eye className="h-4 w-4" />,
        type: "string",
      },
      {
        key: "image_max_bytes",
        label: "发送图片的文件大小上限",
        desc: "单张请求图片的编码字节上限；超出时会自动降低质量。",
        icon: <Gauge className="h-4 w-4" />,
        type: "int",
        min: 1,
        unit: "字节",
      },
      {
        key: "image_files_api",
        label: "Files API 传输",
        desc: "自动时仅向明确支持的端点上传 file_id，失败会回退为内联图片。",
        icon: <Eye className="h-4 w-4" />,
        type: "select",
        options: [
          { value: "auto", label: "自动" },
          { value: "true", label: "强制开启" },
          { value: "false", label: "关闭" },
        ],
      },
    ],
  },
];
