"""Generate web wire types from the same schemas used by tool disclosure.

Run with --check in CI to reject stale checked-in contracts.
"""

from __future__ import annotations
import argparse
import json
from pathlib import Path
from excelmanus.workbook.observation import observation_schema
from excelmanus.workbook.protocol import ObservationRequest, SCHEMA_VERSION
from excelmanus.workbook.contracts import operation_schema


def ts(schema, root=None):
    root = root or schema
    if "$ref" in schema:
        node = root
        for part in schema["$ref"].removeprefix("#/").split("/"):
            node = node[part]
        return ts(node, root)
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "enum" in schema:
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
    for key in ("oneOf", "anyOf"):
        if key in schema and not schema.get("properties"):
            return " | ".join(f"({ts(s, root)})" for s in schema[key])
    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts({**schema, "type": k}, root) for k in kind)
    if kind == "array":
        return f"Array<{ts(schema.get('items', {}), root)}>"
    if kind == "object" or "properties" in schema:
        props = schema.get("properties", {})
        if not props:
            extra = schema.get("additionalProperties", {})
            return f"Record<string, {ts(extra, root) if isinstance(extra, dict) else 'unknown'}>"
        required = schema.get("required", [])
        return (
            "{ "
            + " ".join(
                f"{json.dumps(k)}{'' if k in required else '?'}: {ts(v, root)};"
                for k, v in props.items()
            )
            + " }"
        )
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def render():
    schemas = {
        "WorkbookObservationWire": observation_schema(),
        "ObservationRequestWire": ObservationRequest.model_json_schema(),
        "ChangeOperationWire": operation_schema(),
    }
    return (
        "// Generated by scripts/generate_workbook_contracts.py; do not edit.\n"
        + f"export const WORKBOOK_PROTOCOL = {json.dumps(SCHEMA_VERSION)} as const;\n"
        + "\n".join(
            f"export type {name} = {ts(schema)};" for name, schema in schemas.items()
        )
        + "\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    dest = (
        Path(__file__).resolve().parents[1]
        / "web/src/lib/workbook-contracts.generated.ts"
    )
    output = render()
    if args.check:
        if not dest.exists() or dest.read_text() != output:
            raise SystemExit(
                "Workbook wire types are stale; run python -m scripts.generate_workbook_contracts"
            )
    else:
        dest.write_text(output)
