"""V2 canonical operations: runtime validation and discovery share this schema."""
from __future__ import annotations
from copy import deepcopy
from typing import Any
import jsonschema

OPERATION_SCHEMAS = {'append': {'additionalProperties': False,
            'properties': {'columns': {},
                           'kind': {'enum': ['append'], 'type': 'string'},
                           'sheet': {'type': 'string'},
                           'start_cell': {},
                           'table': {'type': 'string'},
                           'values': {'items': {'items': {}, 'type': 'array'}, 'type': 'array'}},
            'required': ['kind', 'sheet'],
            'type': 'object'},
 'cells.patch': {'additionalProperties': False,
                 'properties': {'cells': {'items': {'additionalProperties': False,
                                                    'anyOf': [{'required': ['value']}, {'required': ['style']}],
                                                    'properties': {'cell': {'type': 'string'},
                                                                   'style': {'type': ['object', 'null']},
                                                                   'value': {'description': 'null 或空串 "" 表示清空该格'}},
                                                    'required': ['cell'],
                                                    'type': 'object'},
                                          'maxItems': 20000,
                                          'minItems': 1,
                                          'type': 'array'},
                                'kind': {'enum': ['cells.patch'], 'type': 'string'},
                                'sheet': {'type': 'string'}},
                 'required': ['kind', 'sheet', 'cells'],
                 'type': 'object'},
 'chart': {'additionalProperties': False,
           'description': 'sheet 指数据源表，target_sheet 指图表放置表。data_range 含系列表头；categories_range 指类别轴。',
           'properties': {'categories_range': {'type': 'string', 'description': '类别轴范围，不含表头；若与 data_range 的边缘行/列重合，会从数据系列排除。'},
                          'chart_type': {'type': 'string'},
                          'data_range': {'type': 'string'},
                          'from_rows': {'type': 'boolean'},
                          'height': {'exclusiveMinimum': 0, 'type': 'number'},
                          'index': {'minimum': 0, 'type': 'integer'},
                          'kind': {'enum': ['chart'], 'type': 'string'},
                          'old_title': {'type': 'string'},
                          'sheet': {'type': 'string', 'description': '数据源工作表，须与 data_range 内表名一致。'},
                          'style': {'type': ['string', 'integer']},
                          'target_cell': {'type': 'string'},
                          'target_sheet': {'type': 'string', 'description': '图表放置工作表，默认与数据源 sheet 相同。'},
                          'title': {'type': 'string'},
                          'width': {'exclusiveMinimum': 0, 'type': 'number'},
                          'x_title': {'type': 'string'},
                          'y_title': {'type': 'string'}},
           'required': ['kind', 'chart_type', 'data_range'],
           'type': 'object'},
 'clear': {'additionalProperties': False,
           'properties': {'kind': {'enum': ['clear'], 'type': 'string'},
                          'mode': {'description': 'clear: values/formats/all; paste_special: '
                                                  'values/formulas/formats/all; fill: copy/series/value',
                                   'type': 'string'},
                          'range': {'type': 'string'},
                          'sheet': {'type': 'string'}},
           'required': ['kind', 'sheet'],
           'type': 'object'},
 'comment': {'additionalProperties': False,
             'properties': {'action': {'enum': ['create', 'update', 'resize', 'delete', 'refresh'],
                                       'type': 'string'},
                            'author': {'type': 'string'},
                            'cell': {'type': 'string'},
                            'columns': {'items': {}, 'type': 'array'},
                            'comment': {'type': 'string'},
                            'display': {'type': 'string'},
                            'height': {'exclusiveMinimum': 0, 'type': 'number'},
                            'hidden': {'type': 'boolean'},
                            'image_path': {'type': 'string'},
                            'index': {'minimum': 0, 'type': 'integer'},
                            'kind': {'enum': ['comment'], 'type': 'string'},
                            'location': {'type': 'string'},
                            'name': {'type': 'string'},
                            'range': {'type': 'string'},
                            'ref': {'type': 'string'},
                            'refers_to': {'type': 'string'},
                            'refresh_on_load': {'type': 'boolean'},
                            'rows': {'items': {}, 'type': 'array'},
                            'scope': {'type': 'string'},
                            'sheet': {'type': 'string'},
                            'show_column_stripes': {'type': 'boolean'},
                            'show_first_column': {'type': 'boolean'},
                            'show_last_column': {'type': 'boolean'},
                            'show_row_stripes': {'type': 'boolean'},
                            'source_range': {'type': 'string'},
                            'source_sheet': {'type': 'string'},
                            'style': {'type': ['string', 'integer']},
                            'target': {'type': 'string'},
                            'target_cell': {'type': 'string'},
                            'target_sheet': {'type': 'string'},
                            'text': {'type': 'string'},
                            'tooltip': {'type': 'string'},
                            'totals_row': {'type': 'boolean'},
                            'values': {'items': {}, 'type': 'array'},
                            'width': {'exclusiveMinimum': 0, 'type': 'number'}},
             'required': ['kind'],
             'type': 'object'},
 'conditional_format': {'additionalProperties': False,
                        'properties': {'kind': {'enum': ['conditional_format'], 'type': 'string'},
                                       'range': {'type': 'string'},
                                       'remove': {'type': 'boolean'},
                                       'rule': {'properties': {'allow_blank': {'type': 'boolean'},
                                                               'bar_color': {'type': 'string'},
                                                               'border': {'additionalProperties': False,
                                                                          'properties': {'bottom': {'additionalProperties': False,
                                                                                                    'properties': {'color': {'type': 'string'},
                                                                                                                   'style': {'type': 'string'}},
                                                                                                    'type': ['object',
                                                                                                             'string']},
                                                                                         'color': {'type': 'string'},
                                                                                         'left': {'additionalProperties': False,
                                                                                                  'properties': {'color': {'type': 'string'},
                                                                                                                 'style': {'type': 'string'}},
                                                                                                  'type': ['object',
                                                                                                           'string']},
                                                                                         'right': {'additionalProperties': False,
                                                                                                   'properties': {'color': {'type': 'string'},
                                                                                                                  'style': {'type': 'string'}},
                                                                                                   'type': ['object',
                                                                                                            'string']},
                                                                                         'style': {'type': 'string'},
                                                                                         'top': {'additionalProperties': False,
                                                                                                 'properties': {'color': {'type': 'string'},
                                                                                                                'style': {'type': 'string'}},
                                                                                                 'type': ['object',
                                                                                                          'string']}},
                                                                          'type': 'object'},
                                                               'error': {'type': 'string'},
                                                               'error_style': {'type': 'string'},
                                                               'error_title': {'type': 'string'},
                                                               'fill': {'additionalProperties': False,
                                                                        'properties': {'color': {'type': 'string'},
                                                                                       'end_color': {'type': 'string'},
                                                                                       'fgColor': {'type': 'string'},
                                                                                       'fg_color': {'type': 'string'},
                                                                                       'fill_type': {'type': 'string'},
                                                                                       'pattern': {'type': 'string'},
                                                                                       'patternType': {'type': 'string'},
                                                                                       'start_color': {'type': 'string'},
                                                                                       'type': {'type': 'string'}},
                                                                        'type': 'object'},
                                                               'font': {'additionalProperties': False,
                                                                        'properties': {'bold': {'type': 'boolean'},
                                                                                       'color': {'type': 'string'},
                                                                                       'italic': {'type': 'boolean'},
                                                                                       'name': {'type': 'string'},
                                                                                       'size': {'type': 'number'},
                                                                                       'strike': {'type': 'boolean'},
                                                                                       'strikethrough': {'type': 'boolean'},
                                                                                       'underline': {'type': 'string'},
                                                                                       'vertAlign': {'enum': ['baseline',
                                                                                                              'superscript',
                                                                                                              'subscript'],
                                                                                                     'type': 'string'}},
                                                                        'type': 'object'},
                                                               'formula': {'items': {'type': 'string'},
                                                                           'maxItems': 1,
                                                                           'minItems': 1,
                                                                           'type': ['string', 'array']},
                                                               'formula1': {},
                                                               'formula2': {},
                                                               'icon_style': {'type': 'string'},
                                                               'max': {},
                                                               'max_color': {'type': 'string'},
                                                               'mid_color': {'type': 'string'},
                                                               'min': {},
                                                               'min_color': {'type': 'string'},
                                                               'n': {'type': 'integer'},
                                                               'operator': {'type': 'string'},
                                                               'prompt': {'type': 'string'},
                                                               'prompt_title': {'type': 'string'},
                                                               'show_dropdown': {'type': 'boolean'},
                                                               'show_error_message': {'type': 'boolean'},
                                                               'show_input_message': {'type': 'boolean'},
                                                               'source': {'type': 'string'},
                                                               'text': {'type': 'string'},
                                                               'type': {'enum': ['cell_value',
                                                                                 'text',
                                                                                 'formula',
                                                                                 'expression',
                                                                                 'duplicate',
                                                                                 'unique',
                                                                                 'top_n',
                                                                                 'bottom_n',
                                                                                 'color_scale',
                                                                                 'data_bar',
                                                                                 'icon_set',
                                                                                 'list',
                                                                                 'dropdown',
                                                                                 'whole',
                                                                                 'int',
                                                                                 'integer',
                                                                                 'decimal',
                                                                                 'float',
                                                                                 'number',
                                                                                 'date',
                                                                                 'time',
                                                                                 'textlength',
                                                                                 'textLength',
                                                                                 'text_length',
                                                                                 'length',
                                                                                 'custom'],
                                                                        'type': 'string'},
                                                               'value': {},
                                                               'value2': {},
                                                               'values': {'type': ['array', 'string']}},
                                                'type': ['object', 'string']},
                                       'sheet': {'type': 'string'}},
                        'required': ['kind'],
                        'type': 'object'},
 'copy': {'additionalProperties': False,
          'properties': {'kind': {'enum': ['copy'], 'type': 'string'},
                         'sheet': {'type': 'string'},
                         'source_range': {'type': 'string'},
                         'source_sheet': {'type': 'string'},
                         'target_sheet': {'type': 'string'},
                         'target_start': {'type': 'string'}},
          'required': ['kind'],
          'type': 'object'},
 'data_validation': {'additionalProperties': False,
                     'properties': {'kind': {'enum': ['data_validation'], 'type': 'string'},
                                    'range': {'type': 'string'},
                                    'remove': {'type': 'boolean'},
                                    'rule': {'properties': {'allow_blank': {'type': 'boolean'},
                                                            'bar_color': {'type': 'string'},
                                                            'border': {'additionalProperties': False,
                                                                       'properties': {'bottom': {'additionalProperties': False,
                                                                                                 'properties': {'color': {'type': 'string'},
                                                                                                                'style': {'type': 'string'}},
                                                                                                 'type': ['object',
                                                                                                          'string']},
                                                                                      'color': {'type': 'string'},
                                                                                      'left': {'additionalProperties': False,
                                                                                               'properties': {'color': {'type': 'string'},
                                                                                                              'style': {'type': 'string'}},
                                                                                               'type': ['object',
                                                                                                        'string']},
                                                                                      'right': {'additionalProperties': False,
                                                                                                'properties': {'color': {'type': 'string'},
                                                                                                               'style': {'type': 'string'}},
                                                                                                'type': ['object',
                                                                                                         'string']},
                                                                                      'style': {'type': 'string'},
                                                                                      'top': {'additionalProperties': False,
                                                                                              'properties': {'color': {'type': 'string'},
                                                                                                             'style': {'type': 'string'}},
                                                                                              'type': ['object',
                                                                                                       'string']}},
                                                                       'type': 'object'},
                                                            'error': {'type': 'string'},
                                                            'error_style': {'type': 'string'},
                                                            'error_title': {'type': 'string'},
                                                            'fill': {'additionalProperties': False,
                                                                     'properties': {'color': {'type': 'string'},
                                                                                    'end_color': {'type': 'string'},
                                                                                    'fgColor': {'type': 'string'},
                                                                                    'fg_color': {'type': 'string'},
                                                                                    'fill_type': {'type': 'string'},
                                                                                    'pattern': {'type': 'string'},
                                                                                    'patternType': {'type': 'string'},
                                                                                    'start_color': {'type': 'string'},
                                                                                    'type': {'type': 'string'}},
                                                                     'type': 'object'},
                                                            'font': {'additionalProperties': False,
                                                                     'properties': {'bold': {'type': 'boolean'},
                                                                                    'color': {'type': 'string'},
                                                                                    'italic': {'type': 'boolean'},
                                                                                    'name': {'type': 'string'},
                                                                                    'size': {'type': 'number'},
                                                                                    'strike': {'type': 'boolean'},
                                                                                    'strikethrough': {'type': 'boolean'},
                                                                                    'underline': {'type': 'string'},
                                                                                    'vertAlign': {'enum': ['baseline',
                                                                                                           'superscript',
                                                                                                           'subscript'],
                                                                                                  'type': 'string'}},
                                                                     'type': 'object'},
                                                            'formula': {'items': {'type': 'string'},
                                                                        'maxItems': 1,
                                                                        'minItems': 1,
                                                                        'type': ['string', 'array']},
                                                            'formula1': {},
                                                            'formula2': {},
                                                            'icon_style': {'type': 'string'},
                                                            'max': {},
                                                            'max_color': {'type': 'string'},
                                                            'mid_color': {'type': 'string'},
                                                            'min': {},
                                                            'min_color': {'type': 'string'},
                                                            'n': {'type': 'integer'},
                                                            'operator': {'type': 'string'},
                                                            'prompt': {'type': 'string'},
                                                            'prompt_title': {'type': 'string'},
                                                            'show_dropdown': {'type': 'boolean'},
                                                            'show_error_message': {'type': 'boolean'},
                                                            'show_input_message': {'type': 'boolean'},
                                                            'source': {'type': 'string'},
                                                            'text': {'type': 'string'},
                                                            'type': {'enum': ['cell_value',
                                                                              'text',
                                                                              'formula',
                                                                              'expression',
                                                                              'duplicate',
                                                                              'unique',
                                                                              'top_n',
                                                                              'bottom_n',
                                                                              'color_scale',
                                                                              'data_bar',
                                                                              'icon_set',
                                                                              'list',
                                                                              'dropdown',
                                                                              'whole',
                                                                              'int',
                                                                              'integer',
                                                                              'decimal',
                                                                              'float',
                                                                              'number',
                                                                              'date',
                                                                              'time',
                                                                              'textlength',
                                                                              'textLength',
                                                                              'text_length',
                                                                              'length',
                                                                              'custom'],
                                                                     'type': 'string'},
                                                            'value': {},
                                                            'value2': {},
                                                            'values': {'type': ['array', 'string']}},
                                             'type': ['object', 'string']},
                                    'sheet': {'type': 'string'}},
                     'required': ['kind'],
                     'type': 'object'},
 'defined_name': {'additionalProperties': False,
                  'properties': {'action': {'enum': ['create', 'update', 'resize', 'delete', 'refresh'],
                                            'type': 'string'},
                                 'author': {'type': 'string'},
                                 'cell': {'type': 'string'},
                                 'columns': {'items': {}, 'type': 'array'},
                                 'comment': {'type': 'string'},
                                 'display': {'type': 'string'},
                                 'height': {'exclusiveMinimum': 0, 'type': 'number'},
                                 'hidden': {'type': 'boolean'},
                                 'image_path': {'type': 'string'},
                                 'index': {'minimum': 0, 'type': 'integer'},
                                 'kind': {'enum': ['defined_name'], 'type': 'string'},
                                 'location': {'type': 'string'},
                                 'name': {'type': 'string'},
                                 'range': {'type': 'string'},
                                 'ref': {'type': 'string'},
                                 'refers_to': {'type': 'string'},
                                 'refresh_on_load': {'type': 'boolean'},
                                 'rows': {'items': {}, 'type': 'array'},
                                 'scope': {'type': 'string'},
                                 'sheet': {'type': 'string'},
                                 'show_column_stripes': {'type': 'boolean'},
                                 'show_first_column': {'type': 'boolean'},
                                 'show_last_column': {'type': 'boolean'},
                                 'show_row_stripes': {'type': 'boolean'},
                                 'source_range': {'type': 'string'},
                                 'source_sheet': {'type': 'string'},
                                 'style': {'type': ['string', 'integer']},
                                 'target': {'type': 'string'},
                                 'target_cell': {'type': 'string'},
                                 'target_sheet': {'type': 'string'},
                                 'text': {'type': 'string'},
                                 'tooltip': {'type': 'string'},
                                 'totals_row': {'type': 'boolean'},
                                 'values': {'items': {}, 'type': 'array'},
                                 'width': {'exclusiveMinimum': 0, 'type': 'number'}},
                  'required': ['kind'],
                  'type': 'object'},
 'delete_chart': {'additionalProperties': False,
                  'properties': {'categories_range': {'type': 'string'},
                                 'chart_type': {'type': 'string'},
                                 'data_range': {'type': 'string'},
                                 'from_rows': {'type': 'boolean'},
                                 'height': {'exclusiveMinimum': 0, 'type': 'number'},
                                 'index': {'minimum': 0, 'type': 'integer'},
                                 'kind': {'enum': ['delete_chart'], 'type': 'string'},
                                 'old_title': {'type': 'string'},
                                 'sheet': {'type': 'string'},
                                 'style': {'type': ['string', 'integer']},
                                 'target_cell': {'type': 'string'},
                                 'target_sheet': {'type': 'string'},
                                 'title': {'type': 'string'},
                                 'width': {'exclusiveMinimum': 0, 'type': 'number'},
                                 'x_title': {'type': 'string'},
                                 'y_title': {'type': 'string'}},
                  'required': ['kind'],
                  'type': 'object'},
 'delete_columns': {'additionalProperties': False,
                    'properties': {'at': {},
                                   'column': {'type': 'string'},
                                   'count': {'type': 'integer'},
                                   'kind': {'enum': ['delete_columns'], 'type': 'string'},
                                   'sheet': {'type': 'string'}},
                    'required': ['kind'],
                    'type': 'object'},
 'delete_rows': {'additionalProperties': False,
                 'properties': {'at': {},
                                'column': {'type': 'string'},
                                'content_version': {'type': 'string'},
                                'count': {'type': 'integer'},
                                'kind': {'enum': ['delete_rows'], 'type': 'string'},
                                'selection': {'type': ['object', 'string']},
                                'sheet': {'type': 'string'},
                                'source_rows': {'items': {'type': 'integer'}, 'type': 'array'}},
                 'required': ['kind'],
                 'type': 'object'},
 'fill': {'additionalProperties': False,
          'properties': {'kind': {'enum': ['fill'], 'type': 'string'},
                         'mode': {'description': 'clear: values/formats/all; paste_special: '
                                                 'values/formulas/formats/all; fill: copy/series/value',
                                  'type': 'string'},
                         'range': {'type': 'string'},
                         'sheet': {'type': 'string'},
                         'source_range': {},
                         'start': {},
                         'step': {'type': 'number'},
                         'value': {},
                         'visible_only': {'type': 'boolean'}},
          'required': ['kind', 'sheet'],
          'type': 'object'},
 'format': {'additionalProperties': False,
            'properties': {'alignment': {'additionalProperties': False,
                                         'properties': {'horizontal': {'type': ['string', 'null']},
                                                        'indent': {'minimum': 0, 'type': ['number', 'null']},
                                                        'readingOrder': {'enum': [0, 1, 2],
                                                                         'type': ['integer', 'null']},
                                                        'shrink_to_fit': {'type': ['boolean', 'null']},
                                                        'text_rotation': {'maximum': 180,
                                                                          'minimum': 0,
                                                                          'type': ['integer', 'null']},
                                                        'vertical': {'type': ['string', 'null']},
                                                        'wrap_text': {'type': ['boolean', 'null']}},
                                         'type': 'object'},
                           'border': {'additionalProperties': False,
                                      'properties': {'bottom': {'additionalProperties': False,
                                                                'properties': {'color': {'type': 'string'},
                                                                               'style': {'type': 'string'}},
                                                                'type': ['object', 'string']},
                                                     'color': {'type': 'string'},
                                                     'left': {'additionalProperties': False,
                                                              'properties': {'color': {'type': 'string'},
                                                                             'style': {'type': 'string'}},
                                                              'type': ['object', 'string']},
                                                     'right': {'additionalProperties': False,
                                                               'properties': {'color': {'type': 'string'},
                                                                              'style': {'type': 'string'}},
                                                               'type': ['object', 'string']},
                                                     'style': {'type': 'string'},
                                                     'top': {'additionalProperties': False,
                                                             'properties': {'color': {'type': 'string'},
                                                                            'style': {'type': 'string'}},
                                                             'type': ['object', 'string']}},
                                      'type': 'object'},
                           'fill': {'additionalProperties': False,
                                    'properties': {'color': {'type': 'string'},
                                                   'end_color': {'type': 'string'},
                                                   'fgColor': {'type': 'string'},
                                                   'fg_color': {'type': 'string'},
                                                   'fill_type': {'type': 'string'},
                                                   'pattern': {'type': 'string'},
                                                   'patternType': {'type': 'string'},
                                                   'start_color': {'type': 'string'},
                                                   'type': {'type': 'string'}},
                                    'type': 'object'},
                           'font': {'additionalProperties': False,
                                    'properties': {'bold': {'type': ['boolean', 'null']},
                                                   'color': {'type': ['string', 'null']},
                                                   'italic': {'type': ['boolean', 'null']},
                                                   'name': {'type': ['string', 'null']},
                                                   'size': {'type': ['number', 'null']},
                                                   'strike': {'type': ['boolean', 'null']},
                                                   'underline': {'type': ['string', 'null']},
                                                   'vertAlign': {'enum': ['baseline', 'superscript', 'subscript'],
                                                                 'type': ['string', 'null']}},
                                    'type': 'object'},
                           'kind': {'enum': ['format'], 'type': 'string'},
                           'number_format': {'type': 'string'},
                           'range': {'type': 'string'},
                           'sheet': {'type': 'string'}},
            'required': ['kind'],
            'type': 'object'},
 'freeze': {'additionalProperties': False,
            'properties': {'freeze_panes': {'type': 'string'},
                           'kind': {'enum': ['freeze'], 'type': 'string'},
                           'sheet': {'type': 'string'}},
            'required': ['kind'],
            'type': 'object'},
 'geometry.scale': {'additionalProperties': False,
                    'properties': {'kind': {'enum': ['geometry.scale'], 'type': 'string'},
                                   'range': {'type': 'string'},
                                   'sheet': {'type': 'string'},
                                   'x': {'exclusiveMinimum': 0, 'type': 'number'},
                                   'y': {'exclusiveMinimum': 0, 'type': 'number'}},
                    'required': ['kind', 'sheet', 'range', 'x', 'y'],
                    'type': 'object'},
 'hyperlink': {'additionalProperties': False,
               'properties': {'action': {'enum': ['create', 'update', 'resize', 'delete', 'refresh'],
                                         'type': 'string'},
                              'author': {'type': 'string'},
                              'cell': {'type': 'string'},
                              'columns': {'items': {}, 'type': 'array'},
                              'comment': {'type': 'string'},
                              'display': {'type': 'string'},
                              'height': {'exclusiveMinimum': 0, 'type': 'number'},
                              'hidden': {'type': 'boolean'},
                              'image_path': {'type': 'string'},
                              'index': {'minimum': 0, 'type': 'integer'},
                              'kind': {'enum': ['hyperlink'], 'type': 'string'},
                              'location': {'type': 'string'},
                              'name': {'type': 'string'},
                              'range': {'type': 'string'},
                              'ref': {'type': 'string'},
                              'refers_to': {'type': 'string'},
                              'refresh_on_load': {'type': 'boolean'},
                              'rows': {'items': {}, 'type': 'array'},
                              'scope': {'type': 'string'},
                              'sheet': {'type': 'string'},
                              'show_column_stripes': {'type': 'boolean'},
                              'show_first_column': {'type': 'boolean'},
                              'show_last_column': {'type': 'boolean'},
                              'show_row_stripes': {'type': 'boolean'},
                              'source_range': {'type': 'string'},
                              'source_sheet': {'type': 'string'},
                              'style': {'type': ['string', 'integer']},
                              'target': {'type': 'string'},
                              'target_cell': {'type': 'string'},
                              'target_sheet': {'type': 'string'},
                              'text': {'type': 'string'},
                              'tooltip': {'type': 'string'},
                              'totals_row': {'type': 'boolean'},
                              'values': {'items': {}, 'type': 'array'},
                              'width': {'exclusiveMinimum': 0, 'type': 'number'}},
               'required': ['kind'],
               'type': 'object'},
 'image': {'additionalProperties': False,
           'properties': {'action': {'enum': ['create', 'update', 'resize', 'delete', 'refresh'],
                                     'type': 'string'},
                          'author': {'type': 'string'},
                          'cell': {'type': 'string'},
                          'columns': {'items': {}, 'type': 'array'},
                          'comment': {'type': 'string'},
                          'display': {'type': 'string'},
                          'height': {'exclusiveMinimum': 0, 'type': 'number'},
                          'hidden': {'type': 'boolean'},
                          'image_path': {'type': 'string'},
                          'index': {'minimum': 0, 'type': 'integer'},
                          'kind': {'enum': ['image'], 'type': 'string'},
                          'location': {'type': 'string'},
                          'name': {'type': 'string'},
                          'range': {'type': 'string'},
                          'ref': {'type': 'string'},
                          'refers_to': {'type': 'string'},
                          'refresh_on_load': {'type': 'boolean'},
                          'rows': {'items': {}, 'type': 'array'},
                          'scope': {'type': 'string'},
                          'sheet': {'type': 'string'},
                          'show_column_stripes': {'type': 'boolean'},
                          'show_first_column': {'type': 'boolean'},
                          'show_last_column': {'type': 'boolean'},
                          'show_row_stripes': {'type': 'boolean'},
                          'source_range': {'type': 'string'},
                          'source_sheet': {'type': 'string'},
                          'style': {'type': ['string', 'integer']},
                          'target': {'type': 'string'},
                          'target_cell': {'type': 'string'},
                          'target_sheet': {'type': 'string'},
                          'text': {'type': 'string'},
                          'tooltip': {'type': 'string'},
                          'totals_row': {'type': 'boolean'},
                          'values': {'items': {}, 'type': 'array'},
                          'width': {'exclusiveMinimum': 0, 'type': 'number'}},
           'required': ['kind'],
           'type': 'object'},
 'insert': {'additionalProperties': False,
            'properties': {'at': {},
                           'axis': {'type': 'string'},
                           'count': {'type': 'integer'},
                           'kind': {'enum': ['insert'], 'type': 'string'},
                           'sheet': {'type': 'string'}},
            'required': ['kind'],
            'type': 'object'},
 'merge': {'additionalProperties': False,
           'properties': {'allow_data_loss': {'type': 'boolean'},
                          'kind': {'enum': ['merge'], 'type': 'string'},
                          'range': {'type': 'string'},
                          'sheet': {'type': 'string'}},
           'required': ['kind'],
           'type': 'object'},
 'paste_special': {'additionalProperties': False,
                   'properties': {'kind': {'enum': ['paste_special'], 'type': 'string'},
                                  'mode': {'description': 'clear: values/formats/all; paste_special: '
                                                          'values/formulas/formats/all; fill: copy/series/value',
                                           'type': 'string'},
                                  'sheet': {'type': 'string'},
                                  'source_range': {},
                                  'source_sheet': {},
                                  'target_start': {},
                                  'transpose': {'type': 'boolean'}},
                   'required': ['kind', 'sheet'],
                   'type': 'object'},
 'pivot': {'additionalProperties': False,
           'properties': {'aggfunc': {'type': 'string'},
                          'column': {'type': 'string'},
                          'columns': {},
                          'conditions': {'items': {'additionalProperties': False,
                                                   'properties': {'col': {'type': 'string'},
                                                                  'column': {'type': 'string'},
                                                                  'op': {'type': 'string'},
                                                                  'operator': {'type': 'string'},
                                                                  'value': {}},
                                                   'type': 'object'},
                                         'type': ['array', 'string']},
                          'grand_total': {'type': 'boolean'},
                          'group_by': {},
                          'header_row': {'minimum': 1, 'type': 'integer'},
                          'index': {},
                          'join': {'additionalProperties': False,
                                   'properties': {'columns': {'items': {'type': 'string'},
                                                              'type': ['array', 'string']},
                                                  'expected_version': {'type': 'string'},
                                                  'file_path': {'type': 'string'},
                                                  'header_row': {'type': 'integer'},
                                                  'how': {'enum': ['left',
                                                                   'inner',
                                                                   'right',
                                                                   'outer',
                                                                   'left_anti',
                                                                   'right_anti'],
                                                          'type': 'string'},
                                                  'leftOn': {'type': 'string'},
                                                  'left_on': {'items': {'type': 'string'},
                                                              'type': ['string', 'array']},
                                                  'on': {'items': {'type': 'string'}, 'type': ['string', 'array']},
                                                  'path': {'type': 'string'},
                                                  'rightOn': {'type': 'string'},
                                                  'right_on': {'items': {'type': 'string'},
                                                               'type': ['string', 'array']},
                                                  'sheet': {'type': 'string'},
                                                  'sheet_name': {'type': 'string'}},
                                   'type': ['object', 'string']},
                          'kind': {'enum': ['pivot'], 'type': 'string'},
                          'logic': {'type': 'string'},
                          'margins': {'type': 'boolean'},
                          'margins_name': {'type': 'string'},
                          'new_name': {'type': 'string'},
                          'operator': {'type': 'string'},
                          'overwrite': {'type': 'boolean'},
                          'pivot_columns': {},
                          'pivot_values': {},
                          'refresh': {'type': 'boolean'},
                          'sheet': {'type': 'string'},
                          'target_sheet': {'type': 'string'},
                          'totals': {'type': 'boolean'},
                          'totals_name': {'type': 'string'},
                          'value': {},
                          'values': {'items': {}, 'type': ['array', 'string']}},
           'required': ['kind'],
           'type': 'object'},
 'pivot_refresh': {'additionalProperties': False,
                   'properties': {'kind': {'enum': ['pivot_refresh'], 'type': 'string'},
                                  'new_name': {'type': 'string'},
                                  'overwrite': {'type': 'boolean'},
                                  'sheet': {'type': 'string'},
                                  'target_sheet': {'type': 'string'}},
                   'required': ['kind'],
                   'type': 'object'},
 'pivot_table': {'additionalProperties': False,
                 'properties': {'action': {'enum': ['create', 'update', 'resize', 'delete', 'refresh'],
                                           'type': 'string'},
                                'author': {'type': 'string'},
                                'cell': {'type': 'string'},
                                'columns': {'items': {}, 'type': 'array'},
                                'comment': {'type': 'string'},
                                'display': {'type': 'string'},
                                'height': {'exclusiveMinimum': 0, 'type': 'number'},
                                'hidden': {'type': 'boolean'},
                                'image_path': {'type': 'string'},
                                'index': {'minimum': 0, 'type': 'integer'},
                                'kind': {'enum': ['pivot_table'], 'type': 'string'},
                                'location': {'type': 'string'},
                                'name': {'type': 'string'},
                                'range': {'type': 'string'},
                                'ref': {'type': 'string'},
                                'refers_to': {'type': 'string'},
                                'refresh_on_load': {'type': 'boolean'},
                                'rows': {'items': {}, 'type': 'array'},
                                'scope': {'type': 'string'},
                                'sheet': {'type': 'string'},
                                'show_column_stripes': {'type': 'boolean'},
                                'show_first_column': {'type': 'boolean'},
                                'show_last_column': {'type': 'boolean'},
                                'show_row_stripes': {'type': 'boolean'},
                                'source_range': {'type': 'string'},
                                'source_sheet': {'type': 'string'},
                                'style': {'type': ['string', 'integer']},
                                'target': {'type': 'string'},
                                'target_cell': {'type': 'string'},
                                'target_sheet': {'type': 'string'},
                                'text': {'type': 'string'},
                                'tooltip': {'type': 'string'},
                                'totals_row': {'type': 'boolean'},
                                'values': {'items': {}, 'type': 'array'},
                                'width': {'exclusiveMinimum': 0, 'type': 'number'}},
                 'required': ['kind'],
                 'type': 'object'},
 'print_layout': {'additionalProperties': False,
                  'properties': {'kind': {'enum': ['print_layout'], 'type': 'string'},
                                 'print_layout': {'additionalProperties': False,
                                                  'properties': {'fit_to_height': {'anyOf': [{'maximum': 32767,
                                                                                              'minimum': 0,
                                                                                              'type': 'integer'},
                                                                                             {'type': 'null'}],
                                                                                   'default': None,
                                                                                   'title': 'Fit To Height'},
                                                                 'fit_to_page': {'anyOf': [{'type': 'boolean'},
                                                                                           {'type': 'null'}],
                                                                                 'default': None,
                                                                                 'title': 'Fit To Page'},
                                                                 'fit_to_width': {'anyOf': [{'maximum': 32767,
                                                                                             'minimum': 0,
                                                                                             'type': 'integer'},
                                                                                            {'type': 'null'}],
                                                                                  'default': None,
                                                                                  'title': 'Fit To Width'},
                                                                 'orientation': {'anyOf': [{'enum': ['portrait',
                                                                                                     'landscape'],
                                                                                            'type': 'string'},
                                                                                           {'type': 'null'}],
                                                                                 'default': None,
                                                                                 'title': 'Orientation'},
                                                                 'paper_size': {'anyOf': [{'enum': ['A3',
                                                                                                    'A4',
                                                                                                    'A5',
                                                                                                    'Letter',
                                                                                                    'Legal'],
                                                                                           'type': 'string'},
                                                                                          {'type': 'null'}],
                                                                                'default': None,
                                                                                'title': 'Paper Size'},
                                                                 'print_area': {'anyOf': [{'type': 'string'},
                                                                                          {'type': 'null'}],
                                                                                'default': None,
                                                                                'title': 'Print Area'},
                                                                 'scale': {'anyOf': [{'maximum': 400,
                                                                                      'minimum': 10,
                                                                                      'type': 'integer'},
                                                                                     {'type': 'null'}],
                                                                           'default': None,
                                                                           'title': 'Scale'}},
                                                  'title': 'PrintLayout',
                                                  'type': 'object'},
                                 'sheet': {'type': 'string'}},
                  'required': ['kind'],
                  'type': 'object'},
 'replace': {'additionalProperties': False,
             'properties': {'find': {},
                            'include_formulas': {'type': 'boolean'},
                            'kind': {'enum': ['replace'], 'type': 'string'},
                            'match_case': {'type': 'boolean'},
                            'range': {'type': 'string'},
                            'regex': {'type': 'boolean'},
                            'replacement': {},
                            'sheet': {'type': 'string'}},
             'required': ['kind', 'sheet'],
             'type': 'object'},
 'sheet': {'additionalProperties': False,
           'properties': {'action': {'type': 'string'},
                          'kind': {'enum': ['sheet'], 'type': 'string'},
                          'new_name': {'type': 'string'},
                          'sheet': {'type': 'string'}},
           'required': ['kind'],
           'type': 'object'},
 'size': {'additionalProperties': False,
          'allOf': [{'if': {'properties': {'auto_fit': {'const': True}}, 'required': ['auto_fit']},
                     'then': {'required': ['axis', 'range']}}],
          'anyOf': [{'required': ['column_widths']},
                    {'required': ['row_heights']},
                    {'properties': {'auto_fit': {'const': True}}, 'required': ['auto_fit']}],
          'properties': {'auto_fit': {'type': 'boolean'},
                         'axis': {'enum': ['row', 'column'], 'type': 'string'},
                         'column_widths': {'additionalProperties': {'exclusiveMinimum': 0,
                                                                    'maximum': 255,
                                                                    'type': 'number'},
                                           'description': '横向列宽，Excel 字符单位，列字母到数值',
                                           'type': 'object'},
                         'kind': {'enum': ['size'], 'type': 'string'},
                         'range': {'type': 'string'},
                         'row_heights': {'additionalProperties': {'exclusiveMinimum': 0,
                                                                  'maximum': 409.5,
                                                                  'type': 'number'},
                                         'description': '纵向行高，points，1-based 行号到数值',
                                         'type': 'object'},
                         'sheet': {'type': 'string'}},
          'required': ['kind'],
          'type': 'object'},
 'sort': {'additionalProperties': False,
          'properties': {'ascending': {'items': {'type': 'boolean'}, 'type': ['boolean', 'array']},
                         'by': {'items': {}, 'type': ['array', 'string']},
                         'header': {'type': 'boolean'},
                         'kind': {'enum': ['sort'], 'type': 'string'},
                         'range': {'type': 'string'},
                         'sheet': {'type': 'string'},
                         'visible_only': {'type': 'boolean'}},
          'required': ['kind', 'sheet'],
          'type': 'object'},
 'table': {'additionalProperties': False,
           'properties': {'action': {'enum': ['create', 'update', 'resize', 'delete', 'refresh'],
                                     'type': 'string'},
                          'author': {'type': 'string'},
                          'cell': {'type': 'string'},
                          'columns': {'items': {}, 'type': 'array'},
                          'comment': {'type': 'string'},
                          'display': {'type': 'string'},
                          'height': {'exclusiveMinimum': 0, 'type': 'number'},
                          'hidden': {'type': 'boolean'},
                          'image_path': {'type': 'string'},
                          'index': {'minimum': 0, 'type': 'integer'},
                          'kind': {'enum': ['table'], 'type': 'string'},
                          'location': {'type': 'string'},
                          'name': {'type': 'string'},
                          'range': {'type': 'string'},
                          'ref': {'type': 'string'},
                          'refers_to': {'type': 'string'},
                          'refresh_on_load': {'type': 'boolean'},
                          'rows': {'items': {}, 'type': 'array'},
                          'scope': {'type': 'string'},
                          'sheet': {'type': 'string'},
                          'show_column_stripes': {'type': 'boolean'},
                          'show_first_column': {'type': 'boolean'},
                          'show_last_column': {'type': 'boolean'},
                          'show_row_stripes': {'type': 'boolean'},
                          'source_range': {'type': 'string'},
                          'source_sheet': {'type': 'string'},
                          'style': {'type': ['string', 'integer']},
                          'target': {'type': 'string'},
                          'target_cell': {'type': 'string'},
                          'target_sheet': {'type': 'string'},
                          'text': {'type': 'string'},
                          'tooltip': {'type': 'string'},
                          'totals_row': {'type': 'boolean'},
                          'values': {'items': {}, 'type': 'array'},
                          'width': {'exclusiveMinimum': 0, 'type': 'number'}},
           'required': ['kind'],
           'type': 'object'},
 'transform': {'additionalProperties': False,
               'properties': {'action': {'type': 'string'},
                              'column': {'type': 'string'},
                              'delimiter': {'type': 'string'},
                              'header_row': {'minimum': 1, 'type': 'integer'},
                              'into': {},
                              'keep': {'enum': ['first', 'last', 'earliest', 'latest'], 'type': 'string'},
                              'key_columns': {'items': {'type': 'string'}, 'type': 'array'},
                              'key_normalizers': {'additionalProperties': {'enum': ['phone'], 'type': 'string'},
                                                  'type': 'object'},
                              'kind': {'enum': ['transform'], 'type': 'string'},
                              'new_columns': {},
                              'order_by': {'type': 'string'},
                              'sep': {'type': 'string'},
                              'sheet': {'type': 'string'},
                              'transform': {'type': 'string'}},
               'required': ['kind'],
               'type': 'object'},
 'unmerge': {'additionalProperties': False,
             'properties': {'kind': {'enum': ['unmerge'], 'type': 'string'},
                            'range': {'type': 'string'},
                            'sheet': {'type': 'string'}},
             'required': ['kind'],
             'type': 'object'},
 'update_chart': {'additionalProperties': False,
                  'properties': {'categories_range': {'type': 'string'},
                                 'chart_type': {'type': 'string'},
                                 'data_range': {'type': 'string'},
                                 'from_rows': {'type': 'boolean'},
                                 'height': {'exclusiveMinimum': 0, 'type': 'number'},
                                 'index': {'minimum': 0, 'type': 'integer'},
                                 'kind': {'enum': ['update_chart'], 'type': 'string'},
                                 'old_title': {'type': 'string'},
                                 'sheet': {'type': 'string'},
                                 'style': {'type': ['string', 'integer']},
                                 'target_cell': {'type': 'string'},
                                 'target_sheet': {'type': 'string'},
                                 'title': {'type': 'string'},
                                 'width': {'exclusiveMinimum': 0, 'type': 'number'},
                                 'x_title': {'type': 'string'},
                                 'y_title': {'type': 'string'}},
                  'required': ['kind'],
                  'type': 'object'},
 'write': {'additionalProperties': False,
           'anyOf': [{'required': ['start_cell']}, {'required': ['selection']}],
           'properties': {'kind': {'enum': ['write'], 'type': 'string'},
                          'selection': {'type': ['object', 'string']},
                          'sheet': {'type': 'string'},
                          'start_cell': {'type': 'string'},
                          'values': {'oneOf': [{'items': {'items': {}, 'type': 'array'},
                                                'minItems': 1,
                                                'type': 'array'},
                                               {'pattern': '^spill:[0-9a-f]{64}$', 'type': 'string'}],
                                     'description': '矩形二维数组；null 或空串 "" 表示清空该格（Excel 无字面空串单元格）'}},
           'required': ['kind', 'values'],
           'type': 'object'}}

# The object operation schemas above are generated from the historical object
# field table so that the literal remains readable, but V2 must not accept a
# bag of unrelated fields.  Narrow each object kind to its own ChangeSet
# surface after construction.  This is intentionally destructive: old object
# aliases are rejected by the same validator as every other stale operation.
_OBJECT_FIELDS = {
    "table": {"kind", "action", "sheet", "name", "ref", "range", "columns", "totals_row", "style",
               "show_first_column", "show_last_column", "show_row_stripes", "show_column_stripes"},
    "defined_name": {"kind", "action", "sheet", "scope", "name", "refers_to", "ref", "hidden", "comment"},
    "comment": {"kind", "action", "sheet", "cell", "text", "author", "width", "height"},
    "hyperlink": {"kind", "action", "sheet", "cell", "target", "location", "display", "tooltip"},
    "image": {"kind", "action", "sheet", "image_path", "target_cell", "index", "width", "height"},
    "pivot_table": {"kind", "action", "sheet", "target_sheet", "name", "source_sheet", "source_range",
                     "target_cell", "rows", "columns", "values", "refresh_on_load"},
    "update_chart": {"kind", "sheet", "index", "title", "chart_type", "data_range", "categories_range",
                     "target_cell", "target_sheet", "width", "height", "style", "from_rows", "x_title", "y_title"},
    "delete_chart": {"kind", "sheet", "index", "target_cell", "title"},
}
for _object_kind, _fields in _OBJECT_FIELDS.items():
    if _object_kind in OPERATION_SCHEMAS:
        _props = OPERATION_SCHEMAS[_object_kind].get("properties", {})
        OPERATION_SCHEMAS[_object_kind]["properties"] = {
            key: value for key, value in _props.items() if key in _fields
        }

_join = OPERATION_SCHEMAS.get("pivot", {}).get("properties", {}).get("join")
if isinstance(_join, dict) and isinstance(_join.get("properties"), dict):
    for _stale in ("path", "leftOn", "rightOn", "sheet_name"):
        _join["properties"].pop(_stale, None)

for _selection_kind in ("write", "delete_rows"):
    if _selection_kind in OPERATION_SCHEMAS:
        _selection = OPERATION_SCHEMAS[_selection_kind].get("properties", {}).get("selection")
        if isinstance(_selection, dict):
            _selection.clear()
            _selection["type"] = "object"

# Keep the public style contract in sync with the execution layer.  The
# mutation style builder already accepts the Excel/openpyxl spellings below;
# exposing them here prevents a valid SDK call from being rejected by the
# JSON-Schema gate merely because it uses a familiar casing.  ``type`` /
# snake_case remain the canonical WorkbookSpec spellings and callers should
# prefer those names when generating new payloads.
_format_style = OPERATION_SCHEMAS.get("format", {}).get("properties", {})
_font_schema = _format_style.get("font")
if isinstance(_font_schema, dict) and isinstance(_font_schema.get("properties"), dict):
    _font_schema["properties"].setdefault(
        "strikethrough", {"type": ["boolean", "null"], "description": "strike 的别名"}
    )
_alignment_schema = _format_style.get("alignment")
if isinstance(_alignment_schema, dict) and isinstance(_alignment_schema.get("properties"), dict):
    _alignment_schema["properties"].update({
        "horizontalAlignment": {"type": ["string", "null"], "description": "horizontal 的别名"},
        "verticalAlignment": {"type": ["string", "null"], "description": "vertical 的别名"},
        "wrapText": {"type": ["boolean", "null"], "description": "wrap_text 的别名"},
        "shrinkToFit": {"type": ["boolean", "null"], "description": "shrink_to_fit 的别名"},
        "textRotation": {"type": ["integer", "null"], "description": "text_rotation 的别名"},
    })

OPERATION_SCHEMAS["geometry.scale"]["properties"]["preserve_outside"] = {"type":"boolean", "description":"Reject if other occupied/styled cells share resized axes"}
OPERATION_SCHEMAS["geometry.resize"] = {"type":"object", "additionalProperties":False,
    "required":["kind","sheet","axis","sizes"], "properties": {
        "kind":{"const":"geometry.resize"}, "sheet":{"type":"string"}, "axis":{"enum":["column","row"]},
        "sizes":{"type":"object","minProperties":1,"maxProperties":20000,"propertyNames":{"pattern":"^[1-9][0-9]*$"},
                 "additionalProperties":{"type":"number","exclusiveMinimum":0}},
        "unit":{"const":"css_px", "default":"css_px"}}}

OPERATION_SCHEMAS["cells.patch"]["properties"]["cells"]["items"]["properties"]["style"] = {
    "type":["object","null"], "additionalProperties":False,
    "properties":{key:deepcopy(value) for key,value in OPERATION_SCHEMAS["format"]["properties"].items() if key not in {"kind","sheet","range"}}}

for _stale in ("pivot_columns", "pivot_values", "new_name", "totals", "totals_name", "grand_total"):
    OPERATION_SCHEMAS["pivot"]["properties"].pop(_stale, None)
OPERATION_SCHEMAS["freeze"]["required"] = ["kind", "freeze_panes"]
for _rule_kind in ("conditional_format", "data_validation"):
    OPERATION_SCHEMAS[_rule_kind]["properties"]["rule"]["type"] = "object"

def operation_schema() -> dict[str, Any]:
    return {"oneOf": [deepcopy(schema) for schema in OPERATION_SCHEMAS.values()]}


class OperationContractError(ValueError):
    code = "INVALID_ARGS"

    def __init__(self, message: str, index: int | None = None):
        super().__init__(message)
        self.fields = {"committed": False, "operation_index": index} if index is not None else {"committed": False}


def validate_operations(operations: Any) -> list[dict[str, Any]]:
    if not isinstance(operations, list) or not operations:
        raise OperationContractError("operations must be a nonempty array")
    for index, operation in enumerate(operations):
        if not isinstance(operation, dict) or operation.get("kind") not in OPERATION_SCHEMAS:
            raise OperationContractError(f"operations[{index}].kind is required and must identify a registered operation; query the operation schema", index)
        try:
            jsonschema.Draft202012Validator(OPERATION_SCHEMAS[operation["kind"]]).validate(operation)
        except jsonschema.ValidationError as exc:
            location = ".".join(map(str, exc.absolute_path))
            error = OperationContractError(f"operations[{index}].{location}: {exc.message}", index)
            error.fields.update(operation_kind=operation["kind"], partial=False, applied=[])
            if exc.validator == "additionalProperties" and isinstance(exc.instance, dict):
                error.fields["invalid_fields"] = sorted(set(exc.instance) - set(exc.schema.get("properties", {})))
                from difflib import get_close_matches

                declared = sorted(str(key) for key in (exc.schema.get("properties") or {}))
                suggestions = {}
                for invalid in error.fields["invalid_fields"]:
                    matches = get_close_matches(str(invalid), declared, n=1, cutoff=0.45)
                    if matches:
                        suggestions[str(invalid)] = matches[0]
                if suggestions:
                    error.fields["field_suggestions"] = suggestions
                    error.args = (
                        f"{error.args[0]}；可能的规范字段: "
                        + ", ".join(f"{key}→{value}" for key, value in suggestions.items()),
                    )
            raise error from exc
    return deepcopy(operations)
